[WIP] User can post new request
CraftAcademy/reQuest_client pull request #3
Opened 2020-06-15 21:52 UTC by designerofthing

[PT Link](https://www.pivotaltracker.com/story/show/173337427)
```
As a user,
In order to get help,
I would like to be able to post a request for help.

As a user,
In order to be identifiable on the platform
I would like to be able to authenticate myself
```
- Add loginForm component with authorisation flow
- Add a 'new quest' page (component)
- Add a post new quest module where the POST request is made (include params :title, :description as well as headers) 
- Add input for quest title
- Add input for quest description
- Add a bit of styling ( see lofis ) 
- Display error / success-messages

2020-06-15 22:13 UTC, erikbjoern requested changes

2020-06-15 22:13 UTC, erikbjoern commented on src/App.jsx
> +        <Route exact path="/newquests" component={NewQuest} />
the naming here should probably request, since it's from the requester's perspective

2020-06-15 22:13 UTC, erikbjoern commented on src/components/NewQuest.jsx
> +        "http//localhost:3001/api/quests",
we changed the endpoint to /api/requests, to keep them separated.

2020-06-15 22:13 UTC, erikbjoern commented on src/components/NewQuest.jsx
> +    console.log("authenticated: " + authenticated);
console.log() here, intentional?

2020-06-16 06:17 UTC, jysmys commented on src/components/NewQuest.jsx
> +    console.log("authenticated: " + authenticated);
haha yes, Australian

2020-06-16 06:38 UTC, kermit-klein approved these changes

2020-06-16 06:51 UTC, erikbjoern commented on src/components/NewQuest.jsx
> +export default NewQuest;
I think any 'quest' in here should be renamed to 'request', including file name. Just to keep it clear. 'reQuests' when in need of help, 'quests' when helping

2020-06-16 12:32 UTC, erikbjoern approved these changes
It's good, you just have an unnecessary `connect()`

2020-06-16 12:32 UTC, erikbjoern commented on src/components/LoginForm.jsx
> +import { connect, useDispatch, useSelector } from "react-redux";
We don't need to connect() if we use redux hooks! The hooks are already connected.

2020-06-16 12:46 UTC, ViaMarcus requested changes

2020-06-16 12:46 UTC, ViaMarcus commented on cypress/fixtures/post_new_quest.json
> +  "message": "Your reQuest was successfully created!"
You also get the :id of the created request

2020-06-16 12:46 UTC, ViaMarcus commented on src/components/NewRequest.jsx
> +      <div name="Logout">
Currently there is no redirect on logout, this will be needed and it might as well be now

2020-06-16 12:46 UTC, ViaMarcus commented on src/modules/auth.js
> +  jtockURL = "http://localhost:3000/api";
Else if is not needed as test is also using same as dev, so it can be removed

2020-06-16 13:00 UTC, ViaMarcus approved these changes

2020-06-16 13:02 UTC, merged